Script started on Wed Jan  6 10:51:31 2016
[?1034hbash-3.2$ ls
db.sqlite3			manage.py
functional_test.py		notes_day_three_part_two
lists				superlists
bash-3.2$ cd supl[Kerlists
bash-3.2$ ls
__init__.py	settings.py	urls.py		wsgi.py
bash-3.2$ cd ..
bash-3.2$ cd..[K[K ..
bash-3.2$ cd ..
bash-3.2$ ls
Applications	Downloads	Music		notes_day_three
Desktop		Library		Pictures	ottg
Documents	Movies		Public
bash-3.2$ cd ottg/superlists/
bash-3.2$ s[Kls
db.sqlite3			manage.py
functional_test.py		notes_day_three_part_two
lists				superlists
bash-3.2$ lscd ottg/superlists/[C[C[C[C[C[C[C[C[C[Cls[K[Kpythong [K[K functiona[K[K[K[K[K[K[K[K[Kmanage.y[Kpy tests
Unknown command: 'tests'
Type 'manage.py help' for usage.
bash-3.2$ python manage.py tests[K
Creating test database for alias 'default'...
F...
======================================================================
FAIL: test_home_page_can_save_a_POST_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 39, in test_home_page_can_save_a_POST_request
    self.assertEqual(Item.objects.count(), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 4 tests in 0.008s

FAILED (failures=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
EE..
======================================================================
ERROR: test_home_page_can_save_a_POST_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 37, in test_home_page_can_save_a_POST_request
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 5, in home_page
    Item = Item()
UnboundLocalError: local variable 'Item' referenced before assignment

======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 27, in test_home_page_returns_correct_html
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 5, in home_page
    Item = Item()
UnboundLocalError: local variable 'Item' referenced before assignment

----------------------------------------------------------------------
Ran 4 tests in 0.003s

FAILED (errors=2)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
....
----------------------------------------------------------------------
Ran 4 tests in 0.010s

OK
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
....
----------------------------------------------------------------------
Ran 4 tests in 0.009s

OK
Destroying test database for alias 'default'...
bash-3.2$ clear
[H[2Jbash-3.2$ clearpython manage.py test
Creating test database for alias 'default'...
.F...
======================================================================
FAIL: test_home_page_doesnt_save_on_GET_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 57, in test_home_page_doesnt_save_on_GET_request
    self.assertEqual(Item.objects.count(), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.013s

FAILED (failures=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
E
======================================================================
ERROR: lists.tests (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: lists.tests
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 6, in <module>
    from lists.views import home_page
  File "/Users/demouser/ottg/superlists/lists/views.py", line 8
    if request.method == 'POST'
                              ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
EEE..
======================================================================
ERROR: test_home_page_can_save_a_POST_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 37, in test_home_page_can_save_a_POST_request
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 16, in home_page
    'new_item_text': item.text,
NameError: global name 'item' is not defined

======================================================================
ERROR: test_home_page_doesnt_save_on_GET_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 56, in test_home_page_doesnt_save_on_GET_request
    home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 16, in home_page
    'new_item_text': item.text,
NameError: global name 'item' is not defined

======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 26, in test_home_page_returns_correct_html
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 16, in home_page
    'new_item_text': item.text,
NameError: global name 'item' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=3)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.....
----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
E....
======================================================================
ERROR: test_home_page_can_save_a_POST_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 45, in test_home_page_can_save_a_POST_request
    self.assertEqual(reponse.status_code, 302)
NameError: global name 'reponse' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (errors=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
F....
======================================================================
FAIL: test_home_page_can_save_a_POST_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 45, in test_home_page_can_save_a_POST_request
    self.assertEqual(response.status_code, 302)
AssertionError: 200 != 302

----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
EEE..
======================================================================
ERROR: test_home_page_can_save_a_POST_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 37, in test_home_page_can_save_a_POST_request
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 10, in home_page
    Item.objects.create(text=new_item_text)
NameError: global name 'new_item_text' is not defined

======================================================================
ERROR: test_home_page_doesnt_save_on_GET_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 62, in test_home_page_doesnt_save_on_GET_request
    home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 17, in home_page
    'new_item_text': new_item_text,
NameError: global name 'new_item_text' is not defined

======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 26, in test_home_page_returns_correct_html
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 17, in home_page
    'new_item_text': new_item_text,
NameError: global name 'new_item_text' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=3)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.EE..
======================================================================
ERROR: test_home_page_doesnt_save_on_GET_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 62, in test_home_page_doesnt_save_on_GET_request
    home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 17, in home_page
    'new_item_text': new_item_text,
NameError: global name 'new_item_text' is not defined

======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 26, in test_home_page_returns_correct_html
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 17, in home_page
    'new_item_text': new_item_text,
NameError: global name 'new_item_text' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (errors=2)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
......
----------------------------------------------------------------------
Ran 6 tests in 0.007s

OK
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.E.....
======================================================================
ERROR: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 67, in test_home_page_displays_all_items
    Items.objects.create(text='itemey 1')
NameError: global name 'Items' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.007s

FAILED (errors=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.EE.E..
======================================================================
ERROR: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 67, in test_home_page_displays_all_items
    Items.objects.create(text='itemey 1')
NameError: global name 'Items' is not defined

======================================================================
ERROR: test_home_page_doesnt_save_on_GET_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 80, in test_home_page_doesnt_save_on_GET_request
    home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 19, in home_page
    items = Item.objects.alL()
AttributeError: 'Manager' object has no attribute 'alL'

======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 26, in test_home_page_returns_correct_html
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 19, in home_page
    items = Item.objects.alL()
AttributeError: 'Manager' object has no attribute 'alL'

----------------------------------------------------------------------
Ran 7 tests in 0.004s

FAILED (errors=3)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.EE.E..
======================================================================
ERROR: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 67, in test_home_page_displays_all_items
    Items.objects.create(text='itemey 1')
NameError: global name 'Items' is not defined

======================================================================
ERROR: test_home_page_doesnt_save_on_GET_request (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 80, in test_home_page_doesnt_save_on_GET_request
    home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 19, in home_page
    items = Item.objects.alL()
AttributeError: 'Manager' object has no attribute 'alL'

======================================================================
ERROR: test_home_page_returns_correct_html (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 26, in test_home_page_returns_correct_html
    response = home_page(request)
  File "/Users/demouser/ottg/superlists/lists/views.py", line 19, in home_page
    items = Item.objects.alL()
AttributeError: 'Manager' object has no attribute 'alL'

----------------------------------------------------------------------
Ran 7 tests in 0.004s

FAILED (errors=3)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.E.....
======================================================================
ERROR: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 67, in test_home_page_displays_all_items
    Items.objects.create(text='itemey 1')
NameError: global name 'Items' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.008s

FAILED (errors=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.E.....
======================================================================
ERROR: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 73, in test_home_page_displays_all_items
    self.assertIn('itemy 1', reponse.content.decode())
NameError: global name 'reponse' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.010s

FAILED (errors=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.F.....
======================================================================
FAIL: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 73, in test_home_page_displays_all_items
    self.assertIn('itemy 1', response.content.decode())
AssertionError: 'itemy 1' not found in u'<!--This is tag -->\n<html>\n<!-- create a tree, To-Do list is inside of title -->\n  <head>\n    <title>To-Do lists</title>\n  </head>\n  <body>\n    <h1>Your To-Do list</h1>\n    <!-- Send info back to htm asked for -->\n    <form method="POST">\n      <!-- get text field -->\n      <input id="id_new_item" name = "item_text" placeholder="Enter a to-do item">\n      <!-- needed if you use a form, if you\'re using the render func you\'re already doing the right thing -->\n      \n    </form>\n    <table id="id_list_table">\n      \n        <tr><td>1. itemey 1</td></tr>\n        \n        <tr><td>1. itemy 2</td></tr>\n        \n    </table>\n  </body>\n<!-- Close HTML tag -->\n</html>\n<!-- Ending with a new line is an issue -->\n\n<!-- Cross-Site Request Forger CSRF -->\n'

----------------------------------------------------------------------
Ran 7 tests in 0.009s

FAILED (failures=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.E.....
======================================================================
ERROR: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 67, in test_home_page_displays_all_items
    Items.objects.create(text='itemey 1')
NameError: global name 'Items' is not defined

----------------------------------------------------------------------
Ran 7 tests in 0.008s

FAILED (errors=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.F.....
======================================================================
FAIL: test_home_page_displays_all_items (lists.tests.HomePageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/demouser/ottg/superlists/lists/tests.py", line 73, in test_home_page_displays_all_items
    self.assertIn('itemy 1', response.content.decode())
AssertionError: 'itemy 1' not found in u'<!--This is tag -->\n<html>\n<!-- create a tree, To-Do list is inside of title -->\n  <head>\n    <title>To-Do lists</title>\n  </head>\n  <body>\n    <h1>Your To-Do list</h1>\n    <!-- Send info back to htm asked for -->\n    <form method="POST">\n      <!-- get text field -->\n      <input id="id_new_item" name = "item_text" placeholder="Enter a to-do item">\n      <!-- needed if you use a form, if you\'re using the render func you\'re already doing the right thing -->\n      \n    </form>\n    <table id="id_list_table">\n      \n        <tr><td>1. itemey 1</td></tr>\n        \n        <tr><td>1. itemy 2</td></tr>\n        \n    </table>\n  </body>\n<!-- Close HTML tag -->\n</html>\n<!-- Ending with a new line is an issue -->\n\n<!-- Cross-Site Request Forger CSRF -->\n'

----------------------------------------------------------------------
Ran 7 tests in 0.011s

FAILED (failures=1)
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.......
----------------------------------------------------------------------
Ran 7 tests in 0.009s

OK
Destroying test database for alias 'default'...
bash-3.2$ python manage.py test
Creating test database for alias 'default'...
.......
----------------------------------------------------------------------
Ran 7 tests in 0.008s

OK
Destroying test database for alias 'default'...
bash-3.2$ ce[Kler[Kar
[H[2Jbash-3.2$ functional [K_test.py
bash: functional_test.py: command not found
bash-3.2$ functional_test.py[C[C[C[C[C[C[C[C[C[C[Kmanage p[Kfumct[K[Knctional[K[K[K[K[K[K[K[K[Knctional_test/[K.py
bash: manage: command not found
bash-3.2$ manage functional_test.py[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[C[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[1Pfunctional_test.py[C[C[C[C[C[C[C[C[C[Cpfunctional_test.py[C[C[C[C[C[C[C[C[C[C[Cyfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[Ctfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[Chfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[Cofunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cnfunctional_test.py[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
bash: pythonfunctional_test.py: command not found
bash-3.2$ pythonfunctional_test.py functional_test.py
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 49, in test_can_start_a_list_and_retrieve_it_later
    self.assertIn('To-Do', self.browser.title)
AssertionError: 'To-Do' not found in u'Problem loading page'

----------------------------------------------------------------------
Ran 1 test in 2.554s

FAILED (failures=1)
bash-3.2$ python functional_test.py[C[C[C[C[C[C[C[C[C[C[Kpython functional_test.py
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 49, in test_can_start_a_list_and_retrieve_it_later
    self.assertIn('To-Do', self.browser.title)
AssertionError: 'To-Do' not found in u'OperationalError at /'

----------------------------------------------------------------------
Ran 1 test in 2.692s

FAILED (failures=1)
bash-3.2$ pythong man[K[K[K[K[K manage.py p[Kmigrate
[36;1mOperations to perform:[0m
[1m  Synchronize unmigrated apps: [0mstaticfiles, messages
[1m  Apply all migrations: [0madmin, contenttypes, lists, auth, sessions
[36;1mSynchronizing apps without migrations:[0m
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
[36;1mRunning migrations:[0m
  Rendering model states...[32;1m DONE[0m
  Applying contenttypes.0001_initial...[32;1m OK[0m
  Applying auth.0001_initial...[32;1m OK[0m
  Applying admin.0001_initial...[32;1m OK[0m
  Applying contenttypes.0002_remove_content_type_name...[32;1m OK[0m
  Applying auth.0002_alter_permission_name_max_length...[32;1m OK[0m
  Applying auth.0003_alter_user_email_max_length...[32;1m OK[0m
  Applying auth.0004_alter_user_username_opts...[32;1m OK[0m
  Applying auth.0005_alter_user_last_login_null...[32;1m OK[0m
  Applying auth.0006_require_contenttypes_0002...[32;1m OK[0m
  Applying lists.0001_initial...[32;1m OK[0m
  Applying lists.0002_item_text...[32;1m OK[0m
  Applying sessions.0001_initial...[32;1m OK[0m
bash-3.2$ python manage.py migratefunctional_test.py
E
======================================================================
ERROR: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 58, in test_can_start_a_list_and_retrieve_it_later
    inputbox.get_attribute('placeholder'), 'Enter a to-do item'
NameError: global name 'inputbox' is not defined

----------------------------------------------------------------------
Ran 1 test in 2.489s

FAILED (errors=1)
bash-3.2$ python functional_test.py
  File "functional_test.py", line 59
    )
    ^
SyntaxError: invalid syntax
bash-3.2$ python functional_test.py
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 78, in test_can_start_a_list_and_retrieve_it_later
    self.check_for_row_in_list_table('Use peacock feathers to make fly')
  File "functional_test.py", line 30, in check_for_row_in_list_table
    self.assertIn(row_text, [row.text for row in rows])
AssertionError: 'Use peacock feathers to make fly' not found in [u'1. Buy peacock feathers', u'1. Use peacock feathers to make fly']

----------------------------------------------------------------------
Ran 1 test in 3.123s

FAILED (failures=1)
bash-3.2$ python functional_test.py
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 68, in test_can_start_a_list_and_retrieve_it_later
    self.check_for_row_in_list_table('1. Buy peacock feathers')
  File "functional_test.py", line 30, in check_for_row_in_list_table
    self.assertIn(row_text, [row.text for row in rows])
AssertionError: '1. Buy peacock feathers' not found in [u'1 Buy peacock feathers', u'2 Use peacock feathers to make fly', u'3 Buy peacock feathers']

----------------------------------------------------------------------
Ran 1 test in 2.904s

FAILED (failures=1)
bash-3.2$ python functional_test.py
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 68, in test_can_start_a_list_and_retrieve_it_later
    self.check_for_row_in_list_table('1. Buy peacock feathers')
  File "functional_test.py", line 30, in check_for_row_in_list_table
    self.assertIn(row_text, [row.text for row in rows])
AssertionError: '1. Buy peacock feathers' not found in [u'1: Buy peacock feathers', u'2: Use peacock feathers to make fly', u'3: Buy peacock feathers', u'4: Buy peacock feathers']

----------------------------------------------------------------------
Ran 1 test in 3.010s

FAILED (failures=1)
bash-3.2$ m[Krm db.sqlite3
bash-3.2$ python manage.py migrate
[36;1mOperations to perform:[0m
[1m  Synchronize unmigrated apps: [0mstaticfiles, messages
[1m  Apply all migrations: [0madmin, contenttypes, lists, auth, sessions
[36;1mSynchronizing apps without migrations:[0m
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
[36;1mRunning migrations:[0m
  Rendering model states...[32;1m DONE[0m
  Applying contenttypes.0001_initial...[32;1m OK[0m
  Applying auth.0001_initial...[32;1m OK[0m
  Applying admin.0001_initial...[32;1m OK[0m
  Applying contenttypes.0002_remove_content_type_name...[32;1m OK[0m
  Applying auth.0002_alter_permission_name_max_length...[32;1m OK[0m
  Applying auth.0003_alter_user_email_max_length...[32;1m OK[0m
  Applying auth.0004_alter_user_username_opts...[32;1m OK[0m
  Applying auth.0005_alter_user_last_login_null...[32;1m OK[0m
  Applying auth.0006_require_contenttypes_0002...[32;1m OK[0m
  Applying lists.0001_initial...[32;1m OK[0m
  Applying lists.0002_item_text...[32;1m OK[0m
  Applying sessions.0001_initial...[32;1m OK[0m
bash-3.2$ python gun[K[K[Kdu[K[Kfunctionaltes[K[K[K_test.[y[K[Kpy
F
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_test.py", line 68, in test_can_start_a_list_and_retrieve_it_later
    self.check_for_row_in_list_table('1. Buy peacock feathers')
  File "functional_test.py", line 30, in check_for_row_in_list_table
    self.assertIn(row_text, [row.text for row in rows])
AssertionError: '1. Buy peacock feathers' not found in [u'1: Buy peacock feathers']

----------------------------------------------------------------------
Ran 1 test in 2.946s

FAILED (failures=1)
bash-3.2$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	[32mmodified:   .gitignore[m
	[32mdeleted:    lists/__init__.pyc[m
	[32mdeleted:    lists/admin.pyc[m
	[32mdeleted:    lists/migrations/0001_initial.pyc[m
	[32mdeleted:    lists/migrations/0002_item_text.pyc[m
	[32mdeleted:    lists/migrations/__init__.pyc[m
	[32mdeleted:    lists/models.pyc[m
	[32mdeleted:    lists/tests.pyc[m
	[32mdeleted:    lists/views.pyc[m
	[32mdeleted:    superlists/__init__.pyc[m
	[32mdeleted:    superlists/settings.pyc[m
	[32mdeleted:    superlists/urls.pyc[m
	[32mdeleted:    superlists/wsgi.pyc[m

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	[31mmodified:   db.sqlite3[m
	[31mmodified:   functional_test.py[m
	[31mmodified:   lists/templates/home.html[m
	[31mmodified:   lists/tests.py[m
	[31mmodified:   lists/views.py[m

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	[31mlists/__init__.pyc[m
	[31mlists/admin.pyc[m
	[31mlists/migrations/0001_initial.pyc[m
	[31mlists/migrations/0002_item_text.pyc[m
	[31mlists/migrations/__init__.pyc[m
	[31mlists/models.pyc[m
	[31mlists/tests.pyc[m
	[31mlists/views.pyc[m
	[31mnotes_day_three_part_two[m
	[31msuperlists/__init__.pyc[m
	[31msuperlists/settings.pyc[m
	[31msuperlists/urls.pyc[m
	[31msuperlists/wsgi.pyc[m

bash-3.2$ git rm db.sqlite3 --force
rm 'db.sqlite3'
bash-3.2$ echo db.d[Ksl[Kqlite4[K3 >> ../.gitignore
bash-3.2$ fi[K[Kgitstatus
bash: gitstatus: command not found
bash-3.2$ gitstatus status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	[32mmodified:   .gitignore[m
	[32mdeleted:    db.sqlite3[m
	[32mdeleted:    lists/__init__.pyc[m
	[32mdeleted:    lists/admin.pyc[m
	[32mdeleted:    lists/migrations/0001_initial.pyc[m
	[32mdeleted:    lists/migrations/0002_item_text.pyc[m
	[32mdeleted:    lists/migrations/__init__.pyc[m
	[32mdeleted:    lists/models.pyc[m
	[32mdeleted:    lists/tests.pyc[m
	[32mdeleted:    lists/views.pyc[m
	[32mdeleted:    superlists/__init__.pyc[m
	[32mdeleted:    superlists/settings.pyc[m
	[32mdeleted:    superlists/urls.pyc[m
	[32mdeleted:    superlists/wsgi.pyc[m

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	[31mmodified:   functional_test.py[m
	[31mmodified:   lists/templates/home.html[m
	[31mmodified:   lists/tests.py[m
	[31mmodified:   lists/views.py[m

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	[31mlists/__init__.pyc[m
	[31mlists/admin.pyc[m
	[31mlists/migrations/0001_initial.pyc[m
	[31mlists/migrations/0002_item_text.pyc[m
	[31mlists/migrations/__init__.pyc[m
	[31mlists/models.pyc[m
	[31mlists/tests.pyc[m
	[31mlists/views.pyc[m
	[31mnotes_day_three_part_two[m
	[31msuperlists/__init__.pyc[m
	[31msuperlists/settings.pyc[m
	[31msuperlists/urls.pyc[m
	[31msuperlists/wsgi.pyc[m

bash-3.2$ git commm[Kit -m [K "Removed sqlite db from git."
[master 03b3a35] Removed sqlite db from git.
 Committer: Demo User <demouser@n245-52.mtholyoke.edu>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 14 files changed, 1 insertion(+)
 delete mode 100644 db.sqlite3
 delete mode 100644 lists/__init__.pyc
 delete mode 100644 lists/admin.pyc
 delete mode 100644 lists/migrations/0001_initial.pyc
 delete mode 100644 lists/migrations/0002_item_text.pyc
 delete mode 100644 lists/migrations/__init__.pyc
 delete mode 100644 lists/models.pyc
 delete mode 100644 lists/tests.pyc
 delete mode 100644 lists/views.pyc
 delete mode 100644 superlists/__init__.pyc
 delete mode 100644 superlists/settings.pyc
 delete mode 100644 superlists/urls.pyc
 delete mode 100644 superlists/wsgi.pyc
bash-3.2$ sta[K[K[Kgit status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	[31mmodified:   functional_test.py[m
	[31mmodified:   lists/templates/home.html[m
	[31mmodified:   lists/tests.py[m
	[31mmodified:   lists/views.py[m

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	[31mlists/__init__.pyc[m
	[31mlists/admin.pyc[m
	[31mlists/migrations/0001_initial.pyc[m
	[31mlists/migrations/0002_item_text.pyc[m
	[31mlists/migrations/__init__.pyc[m
	[31mlists/models.pyc[m
	[31mlists/tests.pyc[m
	[31mlists/views.pyc[m
	[31mnotes_day_three_part_two[m
	[31msuperlists/__init__.pyc[m
	[31msuperlists/settings.pyc[m
	[31msuperlists/urls.pyc[m
	[31msuperlists/wsgi.pyc[m

no changes added to commit (use "git add" and/or "git commit -a")
bash-3.2$ git statuscommit -m "Removed sqlite db from git."[C[C[C[C[C[C[C[C[C[C[C[C[C[Cstatus[Kcommit -m "Removed sqlite db from git."[C[C[C[C[C[C[C[C[C[C[C[C[C[Cstatus[K[Kgit statuscommit -m "Removed sqlite db from git."